// BANCO DE DADOS ÚNICO - Krathus Racing
// Todas as médias, voltas válidas, melhores voltas e posições são CALCULADAS AUTOMATICAMENTE pelo app.js

const database = {
    sessions: [
        {
            id: "Bateria_1_170726",
            name: "Corrida - Bateria 1 (17/07 23:17)",
            date: "17/07/2026 23:17:21",
            type: "Corrida",
            event: "Etapa 1 - Julho",
            laps: [
                { lap: 1, driver: 'DJ', time: 14.629, event: 'Largada em P2' },
                { lap: 1, driver: 'Ronaldo', time: 16.499, event: 'Largada em P1' },
                { lap: 1, driver: 'Raphael', time: 18.892, event: 'Largada em P3' },
                { lap: 2, driver: 'DJ', time: 12.638, event: 'Assumiu P1' },
                { lap: 2, driver: 'Ronaldo', time: 12.136, event: '' },
                { lap: 2, driver: 'Raphael', time: 18.404, event: '' },
                { lap: 3, driver: 'DJ', time: 12.218, event: '' },
                { lap: 3, driver: 'Ronaldo', time: 15.613, event: '' },
                { lap: 3, driver: 'Raphael', time: 205.100, event: 'Incidente em pista (03:25,1)' },
                { lap: 4, driver: 'DJ', time: 12.385, event: '' },
                { lap: 4, driver: 'Ronaldo', time: 16.191, event: '' },
                { lap: 4, driver: 'Raphael', time: 14.887, event: '' },
                { lap: 5, driver: 'DJ', time: 12.040, event: '' },
                { lap: 5, driver: 'Ronaldo', time: 15.321, event: '' },
                { lap: 5, driver: 'Raphael', time: 14.754, event: '' },
                { lap: 6, driver: 'DJ', time: 12.716, event: '' },
                { lap: 6, driver: 'Ronaldo', time: 11.782, event: '' },
                { lap: 6, driver: 'Raphael', time: 11.603, event: 'Melhor volta de Raphael' },
                { lap: 7, driver: 'DJ', time: 12.951, event: '' },
                { lap: 7, driver: 'Ronaldo', time: 14.966, event: '' },
                { lap: 7, driver: 'Raphael', time: 12.893, event: '' },
                { lap: 8, driver: 'DJ', time: 11.966, event: '' },
                { lap: 8, driver: 'Ronaldo', time: 15.030, event: '' },
                { lap: 8, driver: 'Raphael', time: 43.997, event: 'Retenção em pista' },
                { lap: 9, driver: 'DJ', time: 11.855, event: '' },
                { lap: 9, driver: 'Ronaldo', time: 12.854, event: '' },
                { lap: 9, driver: 'Raphael', time: 12.262, event: '' },
                { lap: 10, driver: 'DJ', time: 12.668, event: '' },
                { lap: 10, driver: 'Ronaldo', time: 13.173, event: '' },
                { lap: 10, driver: 'Raphael', time: 15.388, event: 'Encerramento de bateria' },
                { lap: 11, driver: 'DJ', time: 12.265, event: '' },
                { lap: 11, driver: 'Ronaldo', time: 16.636, event: '' },
                { lap: 12, driver: 'DJ', time: 12.574, event: '' },
                { lap: 12, driver: 'Ronaldo', time: 11.703, event: 'Melhor volta de Ronaldo' },
                { lap: 13, driver: 'DJ', time: 12.151, event: '' },
                { lap: 13, driver: 'Ronaldo', time: 12.458, event: '' },
                { lap: 14, driver: 'DJ', time: 12.730, event: '' },
                { lap: 14, driver: 'Ronaldo', time: 12.285, event: '' },
                { lap: 15, driver: 'DJ', time: 12.532, event: '' },
                { lap: 15, driver: 'Ronaldo', time: 12.106, event: '' },
                { lap: 16, driver: 'DJ', time: 13.333, event: '' },
                { lap: 16, driver: 'Ronaldo', time: 16.119, event: '' },
                { lap: 17, driver: 'DJ', time: 12.056, event: '' },
                { lap: 17, driver: 'Ronaldo', time: 12.822, event: '' },
                { lap: 18, driver: 'DJ', time: 12.311, event: '' },
                { lap: 18, driver: 'Ronaldo', time: 14.438, event: '' },
                { lap: 19, driver: 'DJ', time: 15.411, event: '' },
                { lap: 19, driver: 'Ronaldo', time: 11.787, event: '' },
                { lap: 20, driver: 'DJ', time: 10.898, event: 'MELHOR VOLTA ABSOLUTA DA BATERIA (10,898s)' },
                { lap: 20, driver: 'Ronaldo', time: 12.131, event: '' },
                { lap: 21, driver: 'DJ', time: 12.320, event: '' },
                { lap: 21, driver: 'Ronaldo', time: 12.177, event: '' },
                { lap: 22, driver: 'DJ', time: 11.678, event: '' },
                { lap: 22, driver: 'Ronaldo', time: 16.200, event: '' },
                { lap: 23, driver: 'DJ', time: 12.653, event: '' },
                { lap: 23, driver: 'Ronaldo', time: 17.302, event: '' },
                { lap: 24, driver: 'DJ', time: 12.727, event: '' },
                { lap: 24, driver: 'Ronaldo', time: 15.951, event: '' },
                { lap: 25, driver: 'DJ', time: 12.699, event: '' },
                { lap: 25, driver: 'Ronaldo', time: 13.257, event: '' },
                { lap: 26, driver: 'DJ', time: 12.412, event: '' },
                { lap: 26, driver: 'Ronaldo', time: 16.146, event: '' },
                { lap: 27, driver: 'DJ', time: 12.139, event: '' },
                { lap: 28, driver: 'DJ', time: 11.689, event: '' },
                { lap: 29, driver: 'DJ', time: 20.560, event: 'Volta da vitória em P1' }
            ]
        },
        {
            id: "Bateria_2_170726_233919",
            name: "Corrida - Bateria 2 (17/07 23:39)",
            date: "17/07/2026 23:39:19",
            type: "Corrida",
            event: "Etapa 1 - Julho",
            laps: [
                { lap: 1, driver: 'DJ', time: 15.031, event: '' },
                { lap: 1, driver: 'Ronaldo', time: 15.900, event: '' },
                { lap: 1, driver: 'Raphael', time: 16.852, event: '' },
                { lap: 2, driver: 'DJ', time: 14.302, event: '' },
                { lap: 2, driver: 'Ronaldo', time: 15.888, event: '' },
                { lap: 2, driver: 'Raphael', time: 16.665, event: '' },
                { lap: 3, driver: 'DJ', time: 11.998, event: '' },
                { lap: 3, driver: 'Ronaldo', time: 11.925, event: '' },
                { lap: 3, driver: 'Raphael', time: 14.531, event: '' },
                { lap: 4, driver: 'DJ', time: 15.516, event: '' },
                { lap: 4, driver: 'Ronaldo', time: 12.857, event: '' },
                { lap: 4, driver: 'Raphael', time: 12.503, event: '' },
                { lap: 5, driver: 'DJ', time: 12.733, event: '' },
                { lap: 5, driver: 'Ronaldo', time: 11.547, event: '' },
                { lap: 5, driver: 'Raphael', time: 12.964, event: '' },
                { lap: 6, driver: 'DJ', time: 12.325, event: '' },
                { lap: 6, driver: 'Ronaldo', time: 13.154, event: '' },
                { lap: 6, driver: 'Raphael', time: 14.023, event: '' },
                { lap: 7, driver: 'DJ', time: 11.723, event: 'Melhor volta de DJ (11,723s)' },
                { lap: 7, driver: 'Ronaldo', time: 12.150, event: '' },
                { lap: 7, driver: 'Raphael', time: 11.873, event: 'Melhor volta de Raphael (11,873s)' },
                { lap: 8, driver: 'DJ', time: 12.079, event: '' },
                { lap: 8, driver: 'Ronaldo', time: 12.424, event: '' },
                { lap: 8, driver: 'Raphael', time: 16.617, event: '' },
                { lap: 9, driver: 'DJ', time: 13.147, event: '' },
                { lap: 9, driver: 'Ronaldo', time: 13.308, event: '' },
                { lap: 9, driver: 'Raphael', time: 14.425, event: '' },
                { lap: 10, driver: 'DJ', time: 12.260, event: '' },
                { lap: 10, driver: 'Ronaldo', time: 34.863, event: 'Escapada / Incidente em pista (34,863s)' },
                { lap: 10, driver: 'Raphael', time: 15.493, event: '' },
                { lap: 11, driver: 'DJ', time: 13.915, event: '' },
                { lap: 11, driver: 'Ronaldo', time: 11.934, event: '' },
                { lap: 11, driver: 'Raphael', time: 15.085, event: '' },
                { lap: 12, driver: 'DJ', time: 15.157, event: '' },
                { lap: 12, driver: 'Ronaldo', time: 12.308, event: '' },
                { lap: 12, driver: 'Raphael', time: 14.074, event: '' },
                { lap: 13, driver: 'DJ', time: 13.812, event: '' },
                { lap: 13, driver: 'Ronaldo', time: 15.044, event: '' },
                { lap: 13, driver: 'Raphael', time: 16.202, event: '' },
                { lap: 14, driver: 'DJ', time: 12.355, event: '' },
                { lap: 14, driver: 'Ronaldo', time: 12.291, event: '' },
                { lap: 14, driver: 'Raphael', time: 11.965, event: '' },
                { lap: 15, driver: 'DJ', time: 12.136, event: '' },
                { lap: 15, driver: 'Ronaldo', time: 13.008, event: '' },
                { lap: 15, driver: 'Raphael', time: 18.290, event: 'Oscilação (18,290s)' },
                { lap: 16, driver: 'DJ', time: 18.899, event: 'Escapada leve na curva (18,899s)' },
                { lap: 16, driver: 'Ronaldo', time: 12.784, event: '' },
                { lap: 16, driver: 'Raphael', time: 15.660, event: '' },
                { lap: 17, driver: 'DJ', time: 12.689, event: '' },
                { lap: 17, driver: 'Ronaldo', time: 16.284, event: '' },
                { lap: 17, driver: 'Raphael', time: 15.798, event: '' },
                { lap: 18, driver: 'DJ', time: 12.467, event: '' },
                { lap: 18, driver: 'Ronaldo', time: 12.704, event: '' },
                { lap: 18, driver: 'Raphael', time: 12.246, event: '' },
                { lap: 19, driver: 'DJ', time: 12.259, event: '' },
                { lap: 19, driver: 'Ronaldo', time: 13.997, event: '' },
                { lap: 19, driver: 'Raphael', time: 12.831, event: '' },
                { lap: 20, driver: 'DJ', time: 11.980, event: '' },
                { lap: 20, driver: 'Ronaldo', time: 12.521, event: '' },
                { lap: 20, driver: 'Raphael', time: 12.879, event: '' },
                { lap: 21, driver: 'DJ', time: 11.900, event: '' },
                { lap: 21, driver: 'Ronaldo', time: 11.434, event: 'MELHOR VOLTA ABSOLUTA DA BATERIA 2 (11,434s)' },
                { lap: 21, driver: 'Raphael', time: 16.828, event: '' },
                { lap: 22, driver: 'DJ', time: 11.905, event: '' },
                { lap: 22, driver: 'Ronaldo', time: 12.332, event: '' },
                { lap: 22, driver: 'Raphael', time: 13.985, event: '' },
                { lap: 23, driver: 'DJ', time: 15.088, event: '' },
                { lap: 23, driver: 'Ronaldo', time: 12.916, event: '' },
                { lap: 23, driver: 'Raphael', time: 16.371, event: '' },
                { lap: 24, driver: 'DJ', time: 14.033, event: '' },
                { lap: 24, driver: 'Ronaldo', time: 13.286, event: '' },
                { lap: 24, driver: 'Raphael', time: 16.873, event: '' },
                { lap: 25, driver: 'DJ', time: 12.223, event: '' },
                { lap: 25, driver: 'Ronaldo', time: 12.280, event: '' },
                { lap: 25, driver: 'Raphael', time: 12.045, event: '' },
                { lap: 26, driver: 'DJ', time: 12.432, event: '' },
                { lap: 26, driver: 'Ronaldo', time: 12.802, event: '' },
                { lap: 27, driver: 'DJ', time: 12.526, event: '' },
                { lap: 28, driver: 'DJ', time: 11.812, event: 'Volta da vitória em P1' }
            ]
        }
    ]
};
